danielgerlag/workflow-core

src/WorkflowCore/project.json.orig, src/providers/WorkflowCore.LockProviders.Redlock/project.json, src/providers/WorkflowCore.LockProviders.ZooKeeper/project.json, src/providers/WorkflowCore.Persistence.EntityFramework/project.json, src/providers/WorkflowCore.Persistence.MongoDB/project.json, src/providers/WorkflowCore.Persistence.MongoDB/project.json.orig, src/providers/WorkflowCore.Persistence.PostgreSQL/project.json, src/providers/WorkflowCore.Persistence.SqlServer/project.json, src/providers/WorkflowCore.Persistence.Sqlite/project.json, src/providers/WorkflowCore.QueueProviders.RabbitMQ/project.json, src/providers/WorkflowCore.QueueProviders.ZeroMQ/project.json
My team likes workflow core and where it's headed but we unfortunately still need to use the full .net framework.  It looks like the code all still works when targeting net452 so I thought I'd do a pull request and maybe help some others out.
=> Updated project to allow support for net452 framework target

test/WorkflowCore.UnitTests/BasePersistenceFixture.cs
To check the persistence provider if occurs resource competition.
=> [UnitTest] Add ConcurrentPersistWorkflow() test item

src/WorkflowCore/Services/DefaultProviders/MemoryPersistenceProvider.cs
I discovered that my testsuite runs tests in parallel and that caused some problems with the static storage of the MemoryPersistanceProvider.
I had the idea of adding an environment key to the constructor of the provider so that a unique key can be passed in through the WorkflowOptions.PersistanceFactory.
This change is fully backwards compatible since by default the empty string is used as a key and thus will always reach the same environment.
=> Added environments to MemoryPersistanceProvider for parallel testing

src/WorkflowCore/Services/LifeCycleEventPublisher.cs
In the current `LifeCycleEventPublisher` implementation if `_outbox` has some events and `stop` method is called some events would be lost.
=> Use BlockingCollection for LifeCycleEventPublisher

src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs, src/providers/WorkflowCore.QueueProviders.SqlServer/Interfaces/ISqlCommandExecutor.cs, src/providers/WorkflowCore.QueueProviders.SqlServer/Interfaces/ISqlServerQueueProviderMigrator.cs, src/providers/WorkflowCore.QueueProviders.SqlServer/Services/SqlCommandExecutor.cs, src/providers/WorkflowCore.QueueProviders.SqlServer/Services/SqlServerQueueProvider.cs, src/providers/WorkflowCore.QueueProviders.SqlServer/Services/SqlServerQueueProviderMigrator.cs
I added asynchronous method calls for sql and mongodb.
=> async improvement

src/WorkflowCore/Services/BackgroundTasks/EventConsumer.cs, src/WorkflowCore/Services/BackgroundTasks/IndexConsumer.cs, src/WorkflowCore/Services/BackgroundTasks/QueueConsumer.cs, src/WorkflowCore/Services/BackgroundTasks/RunnablePoller.cs, src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs, src/WorkflowCore/Services/CancellationProcessor.cs, src/WorkflowCore/Services/WorkflowExecutor.cs, src/providers/WorkflowCore.Providers.Azure/Services/AzureLockManager.cs
It would be more useful if exception object adds to LogError function. So lots of logging frameworks like NLog can use this object to log. 
I changed all of the LogError function and add exception object to input of this object.
=> Add exception to LogError function

src/WorkflowCore/Interface/IWorkflowHost.cs, src/WorkflowCore/Services/WorkflowHost.cs, src/WorkflowCore/WorkflowCore.csproj
=> Compatibility with IHostedService

docs/json-yaml.md
=> Documentation fix

docs/sagas.md
Swapped first example from "Saga transaction with compensation" with that from "Retry policy for failed saga transaction".
=> Swapped examples.

src/providers/WorkflowCore.Persistence.PostgreSQL/WorkflowCore.Persistence.PostgreSQL.csproj
=> Remove redundant dependency on Npgsql.EntityFrameworkCore.PostgreSQL.Design

src/providers/WorkflowCore.Providers.Azure/README.md, src/providers/WorkflowCore.Providers.Azure/ServiceCollectionExtensions.cs, src/providers/WorkflowCore.Providers.Azure/Services/ServiceBusLifeCycleEventHub.cs, src/providers/WorkflowCore.Providers.Azure/WorkflowCore.Providers.Azure.csproj, src/samples/WorkflowCore.Sample04/Program.cs, src/samples/WorkflowCore.Sample13/Program.cs
Added event hub support using Azure ServiceBus provider.
=> Add Azure ServiceBus provider

src/WorkflowCore.DSL/WorkflowCore.DSL.csproj, src/WorkflowCore/WorkflowCore.csproj, src/providers/WorkflowCore.Providers.AWS/WorkflowCore.Providers.AWS.csproj, src/providers/WorkflowCore.Providers.Elasticsearch/WorkflowCore.Providers.Elasticsearch.csproj, src/providers/WorkflowCore.Providers.Redis/WorkflowCore.Providers.Redis.csproj
Downgrade `Microsoft.Extensions.*`
=> Downgrade Microsoft.Extensions.*

src/WorkflowCore/Interface/IWorkflowRegistry.cs, src/WorkflowCore/Services/WorkflowRegistry.cs, src/WorkflowCore/WorkflowCore.csproj
Adds a `DeregisterWorkflow` method to the default workflow registry implementation.
#491 #438 #370
=> Method to remove definition

WorkflowCore.sln, src/providers/WorkflowCore.Persistence.EntityFramework/WorkflowCore.Persistence.EntityFramework.csproj, src/providers/WorkflowCore.Persistence.MySQL/MigrationContextFactory.cs, src/providers/WorkflowCore.Persistence.MySQL/Migrations/20200223041701_Activities.Designer.cs, src/providers/WorkflowCore.Persistence.MySQL/Migrations/20200223041701_Activities.cs, src/providers/WorkflowCore.Persistence.MySQL/WorkflowCore.Persistence.MySQL.csproj, src/providers/WorkflowCore.Persistence.PostgreSQL/WorkflowCore.Persistence.PostgreSQL.csproj, src/providers/WorkflowCore.Persistence.SqlServer/SqlServerContext.cs, src/providers/WorkflowCore.Persistence.SqlServer/WorkflowCore.Persistence.SqlServer.csproj, src/providers/WorkflowCore.Persistence.Sqlite/WorkflowCore.Persistence.Sqlite.csproj, src/samples/WorkflowCore.Sample01/WorkflowCore.Sample01.csproj, src/samples/WorkflowCore.Sample02/WorkflowCore.Sample02.csproj, src/samples/WorkflowCore.Sample03/WorkflowCore.Sample03.csproj, src/samples/WorkflowCore.Sample04/WorkflowCore.Sample04.csproj, src/samples/WorkflowCore.Sample07/WorkflowCore.Sample07.csproj, src/samples/WorkflowCore.Sample17/WorkflowCore.Sample17.csproj, test/WorkflowCore.Tests.MySQL/DockerSetup.cs, test/WorkflowCore.Tests.PostgreSQL/WorkflowCore.Tests.PostgreSQL.csproj
* Update EF provider libraries
* Add missing MySQL migrations
=> Update EF provider libraries

src/samples/WorkflowCore.Sample03/README.md
Fix readme file "comeplete" to "complete"
=> Spelling correction

README.md
I am new to WorkFlowCore. The README file made me confuse. I add the note in README for others who is new to use WorkFlowCore.
=> Add Using WorkFlowCore.DSL in README YAML&JSON Part

src/providers/WorkflowCore.Providers.AWS/README.md, src/providers/WorkflowCore.Providers.AWS/ServiceCollectionExtensions.cs, src/providers/WorkflowCore.Providers.AWS/Services/SQSQueueProvider.cs, src/providers/WorkflowCore.Providers.AWS/WorkflowCore.Providers.AWS.csproj
=> Add prefix support for AWS Queues

src/WorkflowCore/Interface/IWorkflowRegistry.cs, src/WorkflowCore/Services/WorkflowRegistry.cs
Simple implementation of registry.GetAllDefinitions()
=> #274 add registry.getAllDefinitions to retrieve all registered workflows

src/providers/WorkflowCore.Providers.Redis/ServiceCollectionExtensions.cs, src/providers/WorkflowCore.Providers.Redis/Services/RedisPersistenceProvider.cs, src/providers/WorkflowCore.Providers.Redis/WorkflowCore.Providers.Redis.csproj, test/WorkflowCore.Tests.Redis/RedisPersistenceProviderFixture.cs
option to auto delete complete workflows on redis
=> option to auto delete complete workflows on redis

docs/docs/json-yaml.md
=> add .Decide example into /docs

src/WorkflowCore/Primitives/If.cs, src/WorkflowCore/Primitives/OutcomeSwitch.cs, src/WorkflowCore/Primitives/Schedule.cs, src/WorkflowCore/Primitives/Sequence.cs, src/WorkflowCore/Primitives/When.cs, src/WorkflowCore/Primitives/While.cs, src/WorkflowCore/WorkflowCore.csproj, src/extensions/WorkflowCore.Users/Primitives/UserTask.cs, src/extensions/WorkflowCore.Users/WorkflowCore.Users.csproj
#660 
The default branch was not being passed the current value of the context item.
=> Issue 660: pass current context to default branch

src/WorkflowCore/Services/ErrorHandlers/CompensateHandler.cs, src/WorkflowCore/WorkflowCore.csproj, test/WorkflowCore.IntegrationTests/Scenarios/MultistepCompensationScenario2.cs
Addresses https://github.com/danielgerlag/workflow-core/issues/682#issuecomment-736839077
@MrZoidberg
=> Issue 682: Compensation step sequencing

src/WorkflowCore/Models/WorkflowInstance.cs, src/WorkflowCore/Services/ErrorHandlers/TerminateHandler.cs, src/WorkflowCore/Services/WorkflowController.cs, src/WorkflowCore/Services/WorkflowExecutor.cs
Set CompleteTime to WorkflowInstance when terminating workflow. Resolve https://github.com/danielgerlag/workflow-core/issues/750
=> Set CompleteTime to WorkflowInstance when terminating workflow.

ReleaseNotes/3.4.0.md, src/WorkflowCore/Interface/IWorkflowMiddleware.cs, src/WorkflowCore/Interface/IWorkflowMiddlewareRunner.cs, src/WorkflowCore/Models/WorkflowDefinition.cs, src/WorkflowCore/Services/WorkflowExecutor.cs, src/WorkflowCore/Services/WorkflowMiddlewareRunner.cs, src/WorkflowCore/WorkflowCore.csproj, test/WorkflowCore.UnitTests/Services/WorkflowExecutorFixture.cs, test/WorkflowCore.UnitTests/Services/WorkflowMiddlewareRunnerTests.cs
Hi,
I want to be able to execute post middleware in any workflow status case and not only when is completed.
What do you think? Would this be enough?
We want to build metrics using the post middleware. (execution time, who many workflow completed, suspended, terminated, etc.)
Thanks!
=> Add execute middleware phase

ReleaseNotes/3.4.0.md
Small fix for the `3.4.0` release notes sample.
=> Fix execute workflow phase sample

src/providers/WorkflowCore.Providers.Azure/Interface/ICosmosDbProvisioner.cs, src/providers/WorkflowCore.Providers.Azure/ServiceCollectionExtensions.cs, src/providers/WorkflowCore.Providers.Azure/Services/CosmosDbPersistenceProvider.cs, src/providers/WorkflowCore.Providers.Azure/Services/CosmosDbProvisioner.cs, src/providers/WorkflowCore.Providers.Azure/Services/CosmosDbStorageOptions.cs, src/providers/WorkflowCore.Providers.Azure/WorkflowCore.Providers.Azure.csproj
Allow to pass object with container name
=> Azure Provider - allow to change default container names for Cosmos DB

src/WorkflowCore/Services/ErrorHandlers/SuspendHandler.cs
Added the following line to the SuspendHandler to reset the PersistenceData in the pointer
```csharp
step.PrimeForRetry(pointer);
```
=> Fix issue #871 (Failed Saga container resume issue)

src/WorkflowCore/Primitives/Foreach.cs, test/WorkflowCore.IntegrationTests/Scenarios/ForeachScenario.cs
Added check whether collection is empty.
Foreach step body returns ExecutionResult.Next in case collection is empty as there is nothing to branch from.
**Tests**
Added specific test scenario to ForeachScenario.cs
=> Fix issue 894

src/WorkflowCore/Interface/IWorkflowPurger.cs, src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs, src/providers/WorkflowCore.Persistence.EntityFramework/Services/WorkflowPurger.cs, src/providers/WorkflowCore.Persistence.MongoDB/Services/WorkflowPurger.cs, src/providers/WorkflowCore.Persistence.RavenDB/Services/WorkflowPurger.cs, src/providers/WorkflowCore.Providers.Azure/ServiceCollectionExtensions.cs, src/providers/WorkflowCore.Providers.Azure/Services/WorkflowPurger.cs
**Adding new Purger**
Workflow Core already has Purger for Mongo, EF and Raven. We also want to have it for Azure.
Adding new implementation of interface.
No breaking changes.
=> Adding Azure Cosmos DB Workflow Purger

src/WorkflowCore/Models/WorkflowOptions.cs, src/WorkflowCore/ServiceCollectionExtensions.cs
Fixed typo in PersistanceFactory, it's internal field so change won't affect clients who uses this library
rename PersistanceFactory to PersistenceFactory
**Tests**
No
No
No
=> fix typo in PersistanceFactory

src/providers/WorkflowCore.Providers.Redis/README.md
A clear and concise description of what the change is. Any PR submitted without a description of the change will not be reviewed.
How did you go about implementing the change?
**Tests**
Did you cover your changes with tests?
Do you changes break compatibility with previous versions?
Any additional information you'd like to provide?
=> Fix typo on Redis providers readme

src/Directory.Build.props
=> bump version

.github/workflows/dotnet.yml, src/providers/WorkflowCore.Persistence.MongoDB/README.md, src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs, src/providers/WorkflowCore.Persistence.MongoDB/WorkflowCore.Persistence.MongoDB.csproj, test/Directory.Build.props, test/WorkflowCore.Tests.MongoDB/MongoDockerSetup.cs, test/WorkflowCore.Tests.MongoDB/WorkflowCore.Tests.MongoDB.csproj
Upgraded the MongoDB.Driver to the latest version.
- Upgrade from `MongoDB.Driver` 2.x to 3.x is breaking
- Change of TargetFramework from `netstandard2.0` to `netstandard2.1`is breaking (required by `MongoDB.Driver`)
=> Upgrade MongoDB driver to 3.4.0
