danielgerlag/workflow-core

- src/WorkflowCore/Services/MemoryPersistenceProvider.cs
In some cases, add/remove workflow at persistence store will throw an
exception. ("Collection was modified; enumeration operation may not execute.")
> Lock each list of memory persistence before using

- src/WorkflowCore/Interface/IWorkflowController.cs
- src/WorkflowCore/Services/WorkflowController.cs
- src/WorkflowCore/Services/WorkflowHost.cs
- src/WorkflowCore/WorkflowCore.csproj
- src/extensions/WorkflowCore.WebAPI/Controllers/WorkflowsController.cs
- src/samples/WorkflowCore.Sample01/Program.cs
- src/samples/WorkflowCore.Sample02/Program.cs
- src/samples/WorkflowCore.Sample05/Program.cs
- src/samples/WorkflowCore.Sample06/Program.cs
- src/samples/WorkflowCore.Sample15/Program.cs
- test/WorkflowCore.UnitTests/BasePersistenceFixture.cs
This PR is to address #153 which exposes the WorkflowInstance's 'Reference' property.
Notes:
* A number of unit tests are failing from my end prior to change, I didn't bother with those.  I'm using Rider 2018.1 on Mac.
* Regarding placement of "Reference" argument in  StartWorkflow().  The current placement feels awkward, but it sets up for slightly better compatibility. Preferably, the sequence will be (id, version, reference, data)
* I'm considering updating model builder to index 'Reference'.  But then, probably better to let the end users decide on that.
> Assign workflow instance name/identifier

- src/WorkflowCore/Interface/IWorkflowController.cs
- src/WorkflowCore/Services/WorkflowController.cs
- src/WorkflowCore/Services/WorkflowHost.cs
Since Data for Workflow must have a parameterless constructor, this constraint can be added to `StartWorkflow<TData>`,  so we don't use reflection for creating `Data`
> Remove reflection for creating Data

- src/WorkflowCore/Services/DefinitionStorage/DefinitionLoader.cs
- src/WorkflowCore/Services/FluentBuilders/ExpressionHelpers.cs
- src/WorkflowCore/Services/WorkflowExecutor.cs
- src/samples/WorkflowCore.Sample03/PassingDataWorkflow2.cs
- src/samples/WorkflowCore.Sample03/Program.cs
- test/WorkflowCore.IntegrationTests/Scenarios/DynamicDataIOScenario.cs
- test/WorkflowCore.TestAssets/DataTypes/DynamicData.cs
- test/WorkflowCore.TestAssets/Utils.cs
- test/WorkflowCore.TestAssets/WorkflowCore.TestAssets.csproj
- test/WorkflowCore.TestAssets/stored-dynamic-definition.json
- test/WorkflowCore.Tests.MongoDB/Scenarios/MongoDynamicDataScenario.cs
- test/WorkflowCore.Tests.PostgreSQL/Scenarios/PostgresDynamicDataScenario.cs
- test/WorkflowCore.Tests.SqlServer/Scenarios/SqlServerDynamicDataScenario.cs
- test/WorkflowCore.UnitTests/Services/DefinitionStorage/DefinitionLoaderTests.cs
- test/WorkflowCore.UnitTests/Services/WorkflowExecutorFixture.cs
I recently discovered your library and liked it quite a lot.
However I had a similar use case to issue #95, basically requiring a dynamic data model.
I decided to give a try to extending support for this without breaking old code or changing public interfaces.
My changes would allow any type with an indexer with a string parameter to be used.
You could even mix normal properties and "dynamic" ones.
This code is of course not perfect, so please let me know if you think this would be useful for workflow-core and if you have ideas for improvements.
> Added support for indexers instead of properties for the DataType.

- WorkflowCore.sln
- src/providers/WorkflowCore.Persistence.MySQL/MysqlContext.cs
- src/providers/WorkflowCore.Persistence.MySQL/MysqlContextFactory.cs
- src/providers/WorkflowCore.Persistence.MySQL/README.md
- src/providers/WorkflowCore.Persistence.MySQL/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Persistence.MySQL/WorkflowCore.Persistence.MySQL.csproj
- test/WorkflowCore.Tests.MySQL/DockerSetup.cs
- test/WorkflowCore.Tests.MySQL/MysqlPersistenceProviderFixture.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlBasicScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlDataScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlDynamicDataScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlEventScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlForeachScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlForkScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlIfScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlRetrySagaScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlSagaScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlUserScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlWhenScenario.cs
- test/WorkflowCore.Tests.MySQL/Scenarios/MysqlWhileScenario.cs
- test/WorkflowCore.Tests.MySQL/WorkflowCore.Tests.MySQL.csproj
(This pull request created again because of last one was in wrong branch.)
Hi,
First of all thanks for developing such a good library. I created the MySQL Persistence Provider, but first i want to point out some things:
1. This provider based on Pomelo.EntityFrameworkCore.MySql v2.0.1, only 2.0.1 version can fit in this project.
2. I didn't add migration feature, that's because of a critical migration bug in 2.0.1 version of Pomelo's MySql Provider. PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#393
3. Oracle's EF Core MySQL Provider (MySql.Data.EntityFrameworkCore 6.10.7 ) couldn't be option here, it doesn't support Guid Columns feature and there is no way to make it support that feature, it's based on NET Standard v2.x but it can't be run on .NET Framework 4.6.x either.
Q: How can we …
> Add MySQL Provider

- src/WorkflowCore/Services/WorkflowRegistry.cs
- test/WorkflowCore.UnitTests/Services/WorkflowRegistryFixture.cs
Fixed problem were GetDefinition would throw when called without passing a version and no match for workflowId is found.
The problem was that the call to Max on line 34 throws on an empty enumerable.
I could not resist cleaning up some things in the rest of the file. I hope you don't mind.
> Fixed GetDefinition throwing on missing Workflow

- src/WorkflowCore/Services/WorkflowExecutor.cs
- test/WorkflowCore.UnitTests/Services/WorkflowExecutorFixture.cs
- test/WorkflowCore.UnitTests/WorkflowCore.UnitTests.csproj
This fixes the problem that calling for example:
`Convert.ChangeType(new DataClass(), typeof(object))` throws, even though the conversion should be trivial.
We avoid the problem by just not calling Convert.ChangeType for target Type object.
>  Fixed bug with Convert.ChangeType being called on object type.

- src/WorkflowCore/Interface/IScopeProvider.cs
- src/WorkflowCore/ServiceCollectionExtensions.cs
- src/WorkflowCore/Services/ScopeProvider.cs
- src/WorkflowCore/Services/WorkflowExecutor.cs
- test/WorkflowCore.IntegrationTests/Scenarios/DiScenario.cs
- test/WorkflowCore.IntegrationTests/WorkflowCore.IntegrationTests.csproj
- test/WorkflowCore.Testing/WorkflowTest.cs
- test/WorkflowCore.UnitTests/Services/WorkflowExecutorFixture.cs
Step creation was failing with error "WorkflowCore.Services.WorkflowExecutor:Error: Workflow e8c62d2b-249a-4f25-add5-06771c16b33f raised error on step 0 Message: Cannot resolve 'abc' from root provider because it requires scoped service 'def"
Enhanced code to create a scope for the step execution, so that scoped dependencies can be correctly instantiated before injecting.
> Enhanced to allow scoped dependencies to be injected into steps

- src/WorkflowCore/Services/ErrorHandlers/CompensateHandler.cs
- src/WorkflowCore/Services/ExecutionPointerFactory.cs
- src/WorkflowCore/WorkflowCore.csproj
- src/extensions/WorkflowCore.Users/Primitives/UserTask.cs
- src/extensions/WorkflowCore.Users/WorkflowCore.Users.csproj
- test/WorkflowCore.IntegrationTests/Scenarios/NestedRetrySagaScenario.cs
- test/WorkflowCore.IntegrationTests/Scenarios/RetrySagaWithUserTaskScenario.cs
Addresses the bug with the compensation behavior of nested control structures within a saga, discovered in #258 
@fubar-coder
> Compensation behavior in nested saga

- src/WorkflowCore/Interface/IQueueProvider.cs
- src/WorkflowCore/Interface/IStepBuilder.cs
- src/WorkflowCore/Models/StepOutcome.cs
- src/WorkflowCore/Models/WorkflowDefinition.cs
- src/WorkflowCore/Models/WorkflowStep.cs
- src/WorkflowCore/Models/WorkflowStepCollection.cs
- src/WorkflowCore/Services/DefaultProviders/SingleNodeQueueProvider.cs
- src/WorkflowCore/Services/DefinitionStorage/DefinitionLoader.cs
- src/WorkflowCore/Services/ErrorHandlers/CompensateHandler.cs
- src/WorkflowCore/Services/ExecutionPointerFactory.cs
- src/WorkflowCore/Services/ExecutionResultProcessor.cs
- src/WorkflowCore/Services/FluentBuilders/StepBuilder.cs
- src/WorkflowCore/Services/FluentBuilders/WorkflowBuilder.cs
- src/WorkflowCore/Services/WorkflowExecutor.cs
- src/WorkflowCore/WorkflowCore.csproj
- src/providers/WorkflowCore.Providers.AWS/Services/SQSQueueProvider.cs
- src/providers/WorkflowCore.Providers.AWS/WorkflowCore.Providers.AWS.csproj
- src/providers/WorkflowCore.Providers.Azure/Services/AzureStorageQueueProvider.cs
- src/providers/WorkflowCore.Providers.Azure/WorkflowCore.Providers.Azure.csproj
- src/providers/WorkflowCore.Providers.Redis/Services/RedisQueueProvider.cs
- src/providers/WorkflowCore.Providers.Redis/WorkflowCore.Providers.Redis.csproj
- src/providers/WorkflowCore.QueueProviders.RabbitMQ/Services/RabbitMQProvider.cs
- src/providers/WorkflowCore.QueueProviders.RabbitMQ/WorkflowCore.QueueProviders.RabbitMQ.csproj
- src/providers/WorkflowCore.QueueProviders.SqlServer/Services/QueueConfigProvider.cs
- src/providers/WorkflowCore.QueueProviders.SqlServer/Services/SqlServerQueueProviderMigrator.cs
- src/providers/WorkflowCore.QueueProviders.SqlServer/WorkflowCore.QueueProviders.SqlServer.csproj
- test/WorkflowCore.IntegrationTests/Scenarios/AttachScenario.cs
- test/WorkflowCore.UnitTests/Services/DefinitionStorage/DefinitionLoaderTests.cs
- test/WorkflowCore.UnitTests/Services/WorkflowExecutorFixture.cs
* Added `Attach` and `Id` to fluent API
This will enable one to attach the flow from a step to any other step with an `Id`
Control structure scope will be preserved
```c#
.StartWith<Step1>()
.Id("step1")
.Then<Step2>()
.Attach("step1")    
```
* Added index queue ahead of upcoming feature for async indexing
* Various performance improvements
> Misc improvements

- src/WorkflowCore/Interface/IPersistenceProvider.cs
- src/WorkflowCore/Services/DefaultProviders/MemoryPersistenceProvider.cs
- src/WorkflowCore/Services/DefaultProviders/TransientMemoryPersistenceProvider.cs
- src/providers/WorkflowCore.Persistence.EntityFramework/Services/EntityFrameworkPersistenceProvider.cs
- src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs
- src/providers/WorkflowCore.Providers.AWS/Services/DynamoPersistenceProvider.cs
- src/providers/WorkflowCore.Providers.Redis/Services/RedisPersistenceProvider.cs
- test/WorkflowCore.UnitTests/BasePersistenceFixture.cs
Added the possibility to get multiple workflow instances by a list of ids ( issue #261 )
> add support to get multiple workflow instances by a list of ids

- src/WorkflowCore/Services/ExecutionResultProcessor.cs
- test/WorkflowCore.IntegrationTests/Scenarios/DynamicDataIOScenario.cs
- test/WorkflowCore.IntegrationTests/Scenarios/FailingSagaScenario.cs
This PR changes the default retry behavior for steps within a saga to bubble up to the saga container.
@fubar-coder #258
> Default retry behavior inside saga

- src/WorkflowCore/Services/BackgroundTasks/EventConsumer.cs
- test/WorkflowCore.IntegrationTests/Scenarios/EventOrderScenario.cs
Fix the order of processing for multiple events with same name/key
#146
> Event order

- src/samples/WebApiSample/WebApiSample/Controllers/EventsController.cs
- src/samples/WebApiSample/WebApiSample/Properties/launchSettings.json
- src/samples/WebApiSample/WebApiSample/Startup.cs
- src/samples/WebApiSample/WebApiSample/WebApiSample.csproj
EventsController in WebApiSample is receiving event data as JObject, but TestWorkFlow is trying to cast data to string. This would probably cause headache when first opening the WebApiSample.
> chore(sample): Improve WebApiSample, adding SwaggerUI, fix invalid cast from JObject

- src/WorkflowCore/Services/WorkflowHost.cs
Typo in a log message has been fixed (WorkflowHost.cs)
"Starting backgroud tasks" -> "Starting background tasks"
> Typo in a log message has been fixed (WorkflowHost.cs)

- src/providers/WorkflowCore.Persistence.PostgreSQL/MigrationContextFactory.cs
- src/providers/WorkflowCore.Persistence.PostgreSQL/PostgresContext.cs
- src/providers/WorkflowCore.Persistence.PostgreSQL/PostgresContextFactory.cs
- src/providers/WorkflowCore.Persistence.PostgreSQL/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Persistence.PostgreSQL/WorkflowCore.Persistence.PostgreSQL.csproj
- test/WorkflowCore.Tests.PostgreSQL/PostgresPersistenceProviderFixture.cs
Made the schema name parameterized without changing too much. I can also make method overloads if this solution is less optimal
> Fix issue # 332

- ReleaseNotes/2.1.2.md
- WorkflowCore.sln
- src/WorkflowCore/Interface/IWorkflowPurger.cs
- src/WorkflowCore/WorkflowCore.csproj
- src/providers/WorkflowCore.Persistence.EntityFramework/Services/WorkflowPurger.cs
- src/providers/WorkflowCore.Persistence.EntityFramework/WorkflowCore.Persistence.EntityFramework.csproj
- src/providers/WorkflowCore.Persistence.MongoDB/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs
- src/providers/WorkflowCore.Persistence.MongoDB/Services/WorkflowPurger.cs
- src/providers/WorkflowCore.Persistence.MongoDB/WorkflowCore.Persistence.MongoDB.csproj
- src/providers/WorkflowCore.Persistence.MySQL/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Persistence.MySQL/WorkflowCore.Persistence.MySQL.csproj
- src/providers/WorkflowCore.Persistence.PostgreSQL/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Persistence.PostgreSQL/WorkflowCore.Persistence.PostgreSQL.csproj
- src/providers/WorkflowCore.Persistence.SqlServer/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Persistence.SqlServer/WorkflowCore.Persistence.SqlServer.csproj
- src/providers/WorkflowCore.Persistence.Sqlite/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Persistence.Sqlite/WorkflowCore.Persistence.Sqlite.csproj
This PR adds a feature to purge old workflows from the persistence store.
New `IWorkflowPurger` service that can be injected from the IoC container
```c#
Task PurgeWorkflows(WorkflowStatus status, DateTime olderThan)
```
Implementations are currently only for SQL Server, Postgres and MongoDB
> Workflow purger

- src/providers/WorkflowCore.Persistence.EntityFramework/WorkflowCore.Persistence.EntityFramework.csproj
- src/providers/WorkflowCore.Persistence.PostgreSQL/WorkflowCore.Persistence.PostgreSQL.csproj
- src/providers/WorkflowCore.Persistence.SqlServer/WorkflowCore.Persistence.SqlServer.csproj
* EF Core 3.0 introduces [breaking changes](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md#provider)
* EF Core 3.0 targets .net standard 2.1 which will [not be supported by .Net Framework](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/)
* This PR places an upper limit on the EF core version of the host application, as this incompatibility was creating confusion that workflow core is not compatible with .net core 3.0, which is false
> upper version constraints against ef core 3

- src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs
- Replace create index obsoleted api
- Add convention pack to serialize Enum's as string value (more readable)
> Replce mongo obsolate api and add enum to string convetion

- src/WorkflowCore/Interface/IDateTimeProvider.cs
- src/WorkflowCore/Services/BackgroundTasks/EventConsumer.cs
- src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs
- src/WorkflowCore/Services/DateTimeProvider.cs
- src/WorkflowCore/Services/ErrorHandlers/CompensateHandler.cs
- src/WorkflowCore/Services/ErrorHandlers/RetryHandler.cs
- src/WorkflowCore/Services/ErrorHandlers/SuspendHandler.cs
- src/WorkflowCore/Services/ErrorHandlers/TerminateHandler.cs
- src/WorkflowCore/Services/ExecutionResultProcessor.cs
- src/WorkflowCore/Services/WorkflowExecutor.cs
- test/WorkflowCore.UnitTests/Services/ExecutionResultProcessorFixture.cs
- test/WorkflowCore.UnitTests/Services/WorkflowExecutorFixture.cs
Fix some assignments to EventTimeUtc.
Old version with DateTime.Now.ToUniversalTime was less clear and above an order of magnitude slower.
> Add UtcNow to IDateTimeProvider, and use that throughout.

- ReleaseNotes/3.1.0.md
- WorkflowCore.sln
- docs/control-structures.md
- docs/json-yaml.md
- src/WorkflowCore.DSL/Models/v1/StepSourceV1.cs
- src/WorkflowCore.DSL/Services/DefinitionLoader.cs
- src/WorkflowCore.DSL/WorkflowCore.DSL.csproj
- src/WorkflowCore/Interface/IStepBuilder.cs
- src/WorkflowCore/Interface/IWorkflowBuilder.cs
- src/WorkflowCore/Models/StepOutcome.cs
- src/WorkflowCore/Primitives/Decide.cs
- src/WorkflowCore/Services/FluentBuilders/StepBuilder.cs
- src/WorkflowCore/Services/FluentBuilders/WorkflowBuilder.cs
- src/WorkflowCore/WorkflowCore.csproj
- src/samples/WorkflowCore.Sample12/OutcomeWorkflow.cs
- src/samples/WorkflowCore.Sample12/Program.cs
- src/samples/WorkflowCore.Sample12/README.md
- src/samples/WorkflowCore.Sample18/Program.cs
- test/ScratchPad/HelloWorld.json
- test/ScratchPad/Program.cs
- test/ScratchPad/ScratchPad.csproj
- test/WorkflowCore.IntegrationTests/Scenarios/DecisionScenario.cs
- test/WorkflowCore.IntegrationTests/Scenarios/StoredJsonScenario.cs
- test/WorkflowCore.TestAssets/stored-definition.json
- test/WorkflowCore.Tests.MongoDB/Scenarios/MongoDecisionScenario.cs
- test/WorkflowCore.UnitTests/Services/ExecutionResultProcessorFixture.cs
You can define multiple independent branches within your workflow and select one based on an expression value.
For the fluent API, we define our branches with the `CreateBranch()` method on the workflow builder.  We can then select a branch using the `Decision` step.
This workflow will select `branch1` if the value of `data.Value1` is `one`, and `branch2` if it is `two`.
```c#
var branch1 = builder.CreateBranch()
.StartWith<PrintMessage>()
.Input(step => step.Message, data => "hi from 1")
.Then<PrintMessage>()
.Input(step => step.Message, data => "bye from 1");
var branch2 = builder.CreateBranch()
.StartWith<PrintMessage>()
.Input(step => step.Message, data => "hi from 2")
.Then<PrintMessage>()
.Input(step => step.Message, data => "bye from 2");
builder
.StartWith<HelloWorld>() …
```
> Decision Branching

- src/providers/WorkflowCore.Persistence.SqlServer/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Persistence.SqlServer/SqlContextFactory.cs
- src/providers/WorkflowCore.Persistence.SqlServer/SqlServerContext.cs
- src/providers/WorkflowCore.Persistence.SqlServer/WorkflowCore.Persistence.SqlServer.csproj
#495 @woutervs
Adds init action for Sql context... enabling setting the access token on the Sql connection.
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi
Something like this
```c#
services.AddWorkflow(wf => wf.UseSqlServer(@"Server=.;Database=WorkflowCore;Trusted_Connection=True;", true, true, 
conn => (SqlConnection)conn.AccessToken = ...));
```
> sql context init action

- src/samples/WorkflowCore.Sample08/Program.cs
Fix bug where workflow timer kept running after workflow completed. 
Fix bug where no approval chose yes instead.
> Sample 8: Workflow never stops, can't select 'no' approval

- test/WorkflowCore.Tests.PostgreSQL/DockerSetup.cs
"POSTGRES_HOST_AUTH_METHOD" environment variable is required to start the container
> Fix PostgreSQL environment variables

- src/WorkflowCore/Interface/IWorkflowController.cs
- src/WorkflowCore/Services/WorkflowController.cs
- src/WorkflowCore/Services/WorkflowHost.cs
- src/WorkflowCore/WorkflowCore.csproj
It will be very usefull to can inject services/configuration into Workflow directly.
Example:
```csharp
public class SampleWorkflow : IWorkflow<SampleRequest>
{
private readonly IOptions<WorkflowOptions> _options;
public SampleWorkflow(IOptions<WorkflowOptions> options)
{
_options = options;
}
public string Id => nameof(SampleWorkflow);
public int Version => 1;
public void Build(IWorkflowBuilder<SampleRequest> builder)
{
builder
.StartWith(context => ExecutionResult.Next())
.Then<SampleStep>()
.Input(step => step.Request, data => data)
.OnError(WorkflowErrorHandling.Retry, _options.Value.RetryInterval);
}
}
```
> Allow dependency injection on Workflow

- mkdocs.yml
`Error handing` => `Error handling`
> Fix a little typo in mkdocs

- README.md
- WorkflowCore.sln
- src/WorkflowCore/Interface/IStepBuilder.cs
- src/WorkflowCore/Models/IteratorPersistenceData.cs
- src/WorkflowCore/Primitives/Foreach.cs
- src/WorkflowCore/Services/FluentBuilders/StepBuilder.cs
- src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs
- src/samples/WorkflowCore.Sample09s/ForEachSyncWorkflow.cs
- src/samples/WorkflowCore.Sample09s/Program.cs
- src/samples/WorkflowCore.Sample09s/README.md
- src/samples/WorkflowCore.Sample09s/Steps/DisplayContext.cs
- src/samples/WorkflowCore.Sample09s/Steps/DoSomething.cs
- src/samples/WorkflowCore.Sample09s/Steps/SayGoodbye.cs
- src/samples/WorkflowCore.Sample09s/Steps/SayHello.cs
- src/samples/WorkflowCore.Sample09s/WorkflowCore.Sample09s.csproj
- test/WorkflowCore.IntegrationTests/Scenarios/ForeachSyncScenario.cs
I've seen multiple questions about the ForEach parallel execution and in my use case the TData object defines whether it should run in parallel or synchronous (think a chain of emails for approvals), so I've played around Decide and ForEach vs While but I found it much easier to simply extend the existing ForEach Primitive with a .RunParallel boolean (by default set to True to keep it backward compatible). I think it's a nice addition to this otherwise great library and maybe beneficial to others as well.
I've added the Mongo serialization (only one tested since that's what I use - could not get the other DB Provider tests to run), a new Sample and a link in the readme.
I hope this satisfies your PR requirements and I do hope to see this soon released (obviously I am open to any …
> add foreach.RunParallel option

- src/WorkflowCore/Interface/IStepBuilder.cs
- src/WorkflowCore/Interface/IWorkflowBuilder.cs
- src/WorkflowCore/Interface/IWorkflowModifier.cs
- src/WorkflowCore/Services/FluentBuilders/WorkflowBuilder.cs
This pull request enables users to not start a workflow with `StartWith()` every time, which results in code that's much less boilerplate and that reads smoothier.
> Add possibility to not use `WorkflowBuilder.StartWith()` every time

- src/WorkflowCore/Interface/IScopeProvider.cs
- src/WorkflowCore/Services/ScopeProvider.cs
- src/WorkflowCore/Services/WorkflowExecutor.cs
- test/WorkflowCore.TestAssets/WorkflowCore.TestAssets.csproj
- test/WorkflowCore.UnitTests/Services/ScopeProviderTests.cs
- test/WorkflowCore.UnitTests/Services/WorkflowExecutorFixture.cs
There's use case when you need to take control on how you create a lifetimescope. E.g. if you use Autofac with ServiceProviderFactory, you can override specific dependencies for child scope based on the current context.
#628
> Feature: Context-aware scope for StepBody construction

- src/WorkflowCore/Interface/IStepExecutionContext.cs
- src/WorkflowCore/Interface/IWorkflowExecutor.cs
- src/WorkflowCore/Models/StepExecutionContext.cs
- src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs
- src/WorkflowCore/Services/WorkflowExecutor.cs
Here is small changes to pass primary CancellationToken from the background tasks into any StepBodyAsync classes. It is necessary to make microservices more responsible when stopping IWorkflowHost on long running operations: queries, network requests and etc.
> Pass the CancellationToken into IStepExecutionContext for async steps.

- src/WorkflowCore/ServiceCollectionExtensions.cs
- src/WorkflowCore/Services/WorkflowController.cs
- src/WorkflowCore/Services/WorkflowExecutor.cs
- src/WorkflowCore/WorkflowCore.csproj
- test/WorkflowCore.UnitTests/Services/WorkflowExecutorFixture.cs
Move WorkflowMiddlewareRunner and StepExecutor to be instantiated in a scope specific to the step to avoid potential threading issues when used with EFCore and DbContext.
Fixes bug introduced in #678 and closes issue #709.
> Feature - Scoped Middleware

- src/WorkflowCore/Models/WorkflowOptions.cs
- src/WorkflowCore/ServiceCollectionExtensions.cs
It will be nice to control which background task is starting. In my case i want to separate the workflow poller from workflow consumer.
Setup:
- n x Workflow Producers (this can be achieved by not starting the host and just register the workflow)
- 1 x Workflow Poller (i want to be able to start the host without to have the consumer enabled)
- n x Workflow Consumers (i want to be able to start the host without to have the poller enabled)
The simple way is to add option for each background worker to can disable them and don't register it in DI container.
If you have another idea or thought about this please let me know.
Thanks
**Update:**
Short description of the problem: We are running the workflow host inside the application host and this is deployed in multiple instances. With  enough …
> Tackle consumer starvation

- src/WorkflowCore.DSL/Services/DefinitionLoader.cs
Before, the `StepType` field  must be subclass of `StepBody`
Now,It support for `WorkflowStep`
Old:
```c#
public class HelloWorld : StepBody
```
new:(Add)
```c#
public class EndStep : WorkflowStep
```
It means , In the `YourUserTaskStep`
you can set `ValueOutcome.Value` and control step create in [ProcessExecutionResult](https://github.com/danielgerlag/workflow-core/blob/32fedfd528e9d8f8eeae7a3b9500d84c5c411c39/src/WorkflowCore/Services/ExecutionResultProcessor.cs#L65)
> add support for WorkflowStep

- WorkflowCore.sln
- src/providers/WorkflowCore.Persistence.RavenDB/README.md
- src/providers/WorkflowCore.Persistence.RavenDB/RavenStoreOptions.cs
- src/providers/WorkflowCore.Persistence.RavenDB/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Persistence.RavenDB/Services/RavenDbIndexes.cs
- src/providers/WorkflowCore.Persistence.RavenDB/Services/RavendbPersistenceProvider.cs
- src/providers/WorkflowCore.Persistence.RavenDB/Services/WorkflowPurger.cs
- src/providers/WorkflowCore.Persistence.RavenDB/WorkflowCore.Persistence.RavenDB.csproj
I use RavenDB as a database store. So in order to use conductor, I needed a RavenDB persistent store. I created a netstandard2.0 project modeled after the MongoDB provider store, but adapted to work with RavenDB.
> Adding RavenDB persistence provider

- src/providers/WorkflowCore.Persistence.SqlServer/SqlServerContext.cs
fix #694
SqlServer Provider: replace UseSqlServerIdentityColumn with UseIdentityColumn
as per [doc](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#provider-specific-metadata-api-changes)
> SqlServer Provider: replace UseSqlServerIdentityColumn with UseIdentityColumn

- src/providers/WorkflowCore.Persistence.PostgreSQL/WorkflowCore.Persistence.PostgreSQL.csproj
- src/providers/WorkflowCore.Persistence.SqlServer/Migrations/20210109172432_EFCore5.Designer.cs
- src/providers/WorkflowCore.Persistence.SqlServer/Migrations/20210109172432_EFCore5.cs
- src/providers/WorkflowCore.Persistence.SqlServer/WorkflowCore.Persistence.SqlServer.csproj
- src/providers/WorkflowCore.Persistence.Sqlite/WorkflowCore.Persistence.Sqlite.csproj
- src/samples/WorkflowCore.Sample03/WorkflowCore.Sample03.csproj
- src/samples/WorkflowCore.Sample04/WorkflowCore.Sample04.csproj
- src/samples/WorkflowCore.Sample07/WorkflowCore.Sample07.csproj
- src/samples/WorkflowCore.Sample13/WorkflowCore.Sample13.csproj
- src/samples/WorkflowCore.Sample14/WorkflowCore.Sample14.csproj
- src/samples/WorkflowCore.Sample17/WorkflowCore.Sample17.csproj
- test/ScratchPad/ScratchPad.csproj
- test/WorkflowCore.Tests.PostgreSQL/WorkflowCore.Tests.PostgreSQL.csproj
EF Core 5 breaks older SQL Server migrations.
@evolvedlight
> Support breaking EF core 5 changes

- src/providers/WorkflowCore.Providers.Azure/Services/ServiceBusLifeCycleEventHub.cs
- src/providers/WorkflowCore.Providers.Azure/WorkflowCore.Providers.Azure.csproj
We publish messages without a session ID but receive them with a session handler.
This PR changes the Service Bus LifeCycle listener to use message handler instead of session handler.
@glucaci 
@jiripoledna
> Service Bus LifeCycle listener to use message handler instead of session handler

- src/WorkflowCore/Interface/ISyncWorkflowRunner.cs
- src/WorkflowCore/Services/SyncWorkflowRunner.cs
Extend RunWorkflowSync using a CancelationToken.
When used in a controller, it lets you pass the token from the current context and apply its timeout settings
> Extend RunWorkflowSync

- src/WorkflowCore/WorkflowCore.csproj
- src/providers/WorkflowCore.Persistence.MongoDB/README.md
- src/providers/WorkflowCore.Persistence.MongoDB/Services/DataObjectSerializer.cs
- src/providers/WorkflowCore.Persistence.MongoDB/WorkflowCore.Persistence.MongoDB.csproj
- src/samples/WorkflowCore.TestSample01/NUnitTest.cs
- test/WorkflowCore.IntegrationTests/Scenarios/DataIOScenario.cs
- test/WorkflowCore.Testing/WorkflowCore.Testing.csproj
- test/WorkflowCore.Testing/WorkflowTest.cs
See #761. Previous DataObjectSerializer class has many problems listed in the issue. I've fixed this problem by introducing the ability to use class maps for data classes and enriching serialized BSON with type information by using reflection. This is purely optional and old method is used by default.
> Refactored DataObjectSerializer to be able to use decimal value types and BsonRepresentation attributes

- src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs
Because we use a explicit property map MongoDB will not take in consideration the `EnumRepresentationConvention`, that's why we have to set explicit the serializer.
> Fix workflow status MongoDB serialization

- src/WorkflowCore/Interface/Persistence/IEventRepository.cs
- src/WorkflowCore/Interface/Persistence/IPersistenceProvider.cs
- src/WorkflowCore/Interface/Persistence/ISubscriptionRepository.cs
- src/WorkflowCore/Interface/Persistence/IWorkflowRepository.cs
- src/WorkflowCore/Services/BackgroundTasks/EventConsumer.cs
- src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs
- src/WorkflowCore/Services/DefaultProviders/MemoryPersistenceProvider.cs
- src/WorkflowCore/Services/DefaultProviders/TransientMemoryPersistenceProvider.cs
- src/WorkflowCore/Services/SyncWorkflowRunner.cs
- src/providers/WorkflowCore.Persistence.EntityFramework/Services/EntityFrameworkPersistenceProvider.cs
- src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs
- src/providers/WorkflowCore.Persistence.RavenDB/Services/RavendbPersistenceProvider.cs
- src/providers/WorkflowCore.Providers.AWS/Services/DynamoPersistenceProvider.cs
- src/providers/WorkflowCore.Providers.Azure/Services/CosmosDbPersistenceProvider.cs
- src/providers/WorkflowCore.Providers.Redis/Services/RedisPersistenceProvider.cs
CancellationToken +
Change CosmosDB methods to be more async: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.getitemlinqqueryable?view=azure-dotnet#examples
IPersistenceProvider may be used not only in WorkflowCore itself, but maybe injected to custom services with CancellationToken.
**Tests**
There are already tests.
It shouldn't be breaking changes as CancellationToken = default is optional.
@danielgerlag could you please share your thoughts ?
> CancellationToken passed to PersistantStorage providers

- docs/getting-started.md
It was unclear in the JSON and YAML definitions what the related properties of the step and the DTO are. Hopefully I understood it correctly.
> Fixed wrong JSON and YAML definitions in documentation example

- WorkflowCore.sln
- src/WorkflowCore/Interface/IDistributedLockProvider.cs
- src/WorkflowCore/Services/LifeCycleEventPublisher.cs
- src/WorkflowCore/Services/WorkflowHost.cs
- test/WorkflowCore.UnitTests/Services/LifeCycleEventPublisherTests.cs
LifeCycleEventPublisher does not add any events anymore when it is stopped and started again. This PR fixes this behaviour and also attaches lifecycle events again which are removed when stopping the host.
See code
**Tests**
Publisher is covered, Host is not covered.
None.
Related to #844, but does not completely fix the issues described there.
> Fix lifecycle events when restarting Workflow Core

- src/providers/WorkflowCore.Persistence.MongoDB/ServiceCollectionExtensions.cs
This change will allow configuring mongo client, e.g. like subscribing to events for diagnostics.
```csharp
services
.AddWorkflow(o => o.UseMongoDB(dbOptions.ConnectionString, dbOptions.DatabaseName, s =>
{
s.ClusterConfigurator = builder => builder.Subscribe(new MongoDbEventSubscriber());
}));
```
> Allow mongo client configuration

- src/WorkflowCore/Services/BackgroundTasks/EventConsumer.cs
- src/WorkflowCore/Services/BackgroundTasks/RunnablePoller.cs
- src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs
- test/WorkflowCore.IntegrationTests/Scenarios/ParallelEventsScenario.cs
Maybe related to https://github.com/danielgerlag/workflow-core/pull/782
Hi @danielgerlag ,
Let me share some scenario:
Input: Workflow with multiple Parallel steps and in each of it WaitFor tasks.
At some point we are facing next situation:
1. In custom step we are sending some work to process (in our case it is a queue).
2. After that we are adding WaitFor to subscribe on event (and it is working well). Job is returned back even if we didn't subscribe yet for it with WaitFor.
This case if handled in:
But Event is not locked here : https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs#L94
3. After subscription we are reseting event back to unprocessed state. Which is ok.
4. Poller on line: …
> Use lock on event subscription

- src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs
- test/WorkflowCore.IntegrationTests/Scenarios/ParallelEventsScenario.cs
@danielgerlag it is another version of Unit test for Parallel events.
PS. previous version working fine for me, only one reason that I can see that default poller is 10 second and test rely on this, so I decided to change for test timing to be 1 second. Also id on a test was same.
Please let me know if it works for you. Sorry for inconvinience and thank you for library support.
> Parallel Events test fixes

- .github/workflows/dotnet.yml
- src/providers/WorkflowCore.Persistence.MySQL/MysqlContext.cs
- src/providers/WorkflowCore.Persistence.MySQL/WorkflowCore.Persistence.MySQL.csproj
- src/samples/WorkflowCore.Sample04/WorkflowCore.Sample04.csproj
- test/WorkflowCore.Tests.MySQL/DockerSetup.cs
Compatible with net5.0
add mutiple TargetFramework(`netstandard2.0`, `netstandard2.1`) for `WorkflowCore.Persistence.MySQL` project.
**Tests**
yes
no
See #876
> feat: Compatible with net5.0

- src/providers/WorkflowCore.Providers.Elasticsearch/WorkflowCore.Providers.Elasticsearch.csproj
- test/WorkflowCore.Tests.Elasticsearch/WorkflowCore.Tests.Elasticsearch.csproj
Describe the change
fix startup exception "ArgumentException: Requested value 'data_cold' was not found" which the NEST V7.5.1 library doesn't have all new elastic roles enum mappings when use elastic search provider
Describe your implementation or design
How did you go about implementing the change?
only changing version
Tests
Did you cover your changes with tests?
No
Breaking change
Do you changes break compatibility with previous versions?
NO
> Upgrade NEST version to support elastic 7

- test/WorkflowCore.Tests.SqlServer/DockerSetup.cs
The repository` microsoft/mssql-server-linux` is no longer maintained and the container image cannot be pulled.
The `mcr.microsoft.com/mssql/server` should be used instead.
See https://cloudblogs.microsoft.com/sqlserver/2021/05/20/microsoft-sql-server-linux-based-container-images-to-be-available-only-from-the-microsoft-container-registry/ for details.
Without the fix test fail with the following error:
"`pull access denied for microsoft/mssql-server-linux, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`".
> Fix SQL Server tests

- test/WorkflowCore.Tests.DynamoDB/DynamoDbDockerSetup.cs
The recent `amazon/dynamodb-local` images introduce breaking change and require dummy credentials, see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html.
Without the fix, tests fail with the timeout error in `DockerSetup.StartContainer` method but the real error is "`Unable to get IAM security credentials from EC2 Instance Metadata Service.`" in the `DynamoDbDockerSetup.TestReady` method.
> Fix DynamoDB tests

- src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs
Resolve #957. `InsertOneAsync` will throw a `MongoWriteException` and not a `MongoBulkWriteException`. Hence the original catch would have never triggered.
- Changed `MongoBulkWriteException` to `MongoWriteException` and changed the check on the `WriteErrors` property to a check on `WriteError`. 
- Also changed the `.` to `?.` (if the error is a WriteConcernError, the `WriteError` property won't be set)
**Tests**
I couldn't find any automated tests to modify in WorkflowCore.Tests.MongoDB, so I manually tested it (i.e. made sure the `MongoWriteException` is triggered, caught and ignored)
NOT a breaking change
None
> Resolve #957, E11000 duplicate key error

- .github/workflows/dotnet.yml
- src/WorkflowCore/WorkflowCore.csproj
This PR is aimed to fix the failing GitHub actions build, which might be beneficial for the fork maintainers and for the original repository.
It includes three fixes:
- Use .NET SDK 3.1 instead of .NET SDK 5 since sample projects target 3.1 (yet?).
- Disable parallel tests to avoid race conditions since some code is not expected to be thread-safe.
- Change the `InternalsVisibleTo` attribute so it works on GitHub build.
Please let me know if it can be improved/extended.
> Fix GitHub actions build.

- src/providers/WorkflowCore.Persistence.EntityFramework/WorkflowCore.Persistence.EntityFramework.csproj
- src/providers/WorkflowCore.Persistence.MySQL/WorkflowCore.Persistence.MySQL.csproj
- src/providers/WorkflowCore.Persistence.PostgreSQL/WorkflowCore.Persistence.PostgreSQL.csproj
- src/providers/WorkflowCore.Persistence.SqlServer/WorkflowCore.Persistence.SqlServer.csproj
- src/providers/WorkflowCore.Persistence.Sqlite/WorkflowCore.Persistence.Sqlite.csproj
- src/samples/WorkflowCore.Sample03/WorkflowCore.Sample03.csproj
- src/samples/WorkflowCore.Sample04/WorkflowCore.Sample04.csproj
- src/samples/WorkflowCore.Sample07/WorkflowCore.Sample07.csproj
- src/samples/WorkflowCore.Sample17/WorkflowCore.Sample17.csproj
- test/WorkflowCore.Tests.PostgreSQL/WorkflowCore.Tests.PostgreSQL.csproj
Seams that no persistence provider is working with .NET6.0.
To remain compatible with current clients and to don't introduce any braking change I've added .NET6 as additional target and conditionally update the packages.
> Fix EntityFramework dependend providers for .NET6

- src/providers/WorkflowCore.Providers.Redis/Services/RedisQueueProvider.cs
There's an issue with having duplicates in Redis queue. After polling runnable workflows it can have thousands of duplicated records. When you add new workflows, they are added at the end of the list and can be started only when all duplicates are checked that they are processed, in my environment it takes minutes and hours. Application is just checking duplicates and doing nothing.
This change works in this way:
1. Try to add an Id before the same Id.
2. If the Id is not found (-1) or the list is empty (0) then just push the Id to the list as before.
3. If an existing item is found and the duplicate is inserted, then remove the first 1 value from the list (actually the item we added).
> Do not push duplicates to Redis queue, simulate unique list behavior

- src/providers/WorkflowCore.Providers.Redis/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Providers.Redis/Services/RedisLockProvider.cs
We use the same Redis connection string for all services which run WorkflowCore and have their own databases.
Current behavior locks other services from polling runnable workflows, events, etc. It uses on key to lock for different services.
Adding prefix can solve this problem.
And I also found that there's an open issue to have it.
> Add prefix to RedisLockProvider #1044

- src/WorkflowCore.DSL/Models/v1/StepSourceV1.cs
- src/WorkflowCore.DSL/Services/DefinitionLoader.cs
- test/WorkflowCore.IntegrationTests/Scenarios/StoredJsonScenario.cs
- test/WorkflowCore.IntegrationTests/Scenarios/StoredYamlScenario.cs
- test/WorkflowCore.TestAssets/DataTypes/CounterBoard.cs
- test/WorkflowCore.TestAssets/stored-definition.json
- test/WorkflowCore.TestAssets/stored-definition.yaml
- test/WorkflowCore.TestAssets/stored-dynamic-definition.json
- test/WorkflowCore.TestAssets/stored-dynamic-definition.yaml
Hi Daniel,
during my research to find a way to create a step with deadline, I found some post that suggest to use a .Parallel() with .WaitFor() on one branch and .Sleep() on another branch, and use .CancelCondition(<condition>, **true**) to the Parallel.
I could simulate my scenario and it works perfectly with FluentAPI, but I'm using the JSON Loader extension on WorkflowCore.DSL, and this loader not have how to pass the property "ProceedOnCancel".
So I added property "ProceedOnCancel" to StepSourceV1 and pass it value to the targetStep on ConvertStep at definitionLoader. And also change some tests to contemple this property.
Thank you for this amazing workflow engine.
> Add ProceedOnCancel to WorkflowCore.DSL definition loader

- src/providers/WorkflowCore.Persistence.MySQL/MysqlContext.cs
Hello Daniel,
After the changes on WorkflowCore to run with NET6, MySQL provider stopped working, throwing an error when trying to start de WorkflowCore Host.
The issue only occurs when using MySQL provider with NET6 projects.
After investigating, I found a condition in "MysqlContext" class that validate only NetStandard.
So I'm making a PR and adding the NET6 verification.
Thanks
PS: sorry for open a new PR, I commited some inaproprieted changes at my master and can't revert than, so I deleted my repository and the old PR was closed automatically (old PR #1034 )
> Cannot start WorkflowHost with MySql on NET6, DbContext injection missing

- src/WorkflowCore/Interface/Persistence/IWorkflowRepository.cs
- src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs
- src/WorkflowCore/Services/DefaultProviders/MemoryPersistenceProvider.cs
- src/WorkflowCore/Services/DefaultProviders/TransientMemoryPersistenceProvider.cs
- src/providers/WorkflowCore.Persistence.EntityFramework/Services/EntityFrameworkPersistenceProvider.cs
- src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs
- src/providers/WorkflowCore.Persistence.RavenDB/Services/RavendbPersistenceProvider.cs
- src/providers/WorkflowCore.Providers.AWS/Services/DynamoPersistenceProvider.cs
- src/providers/WorkflowCore.Providers.Azure/Services/CosmosDbPersistenceProvider.cs
- src/providers/WorkflowCore.Providers.Redis/Services/RedisPersistenceProvider.cs
- test/WorkflowCore.UnitTests/BasePersistenceFixture.cs
Fixed consistency of WorkflowConsumer when persisting workflow. 
Persisting workflow instance and subscriptions within single database transaction.
It is needed because if application crashes or stops between ```PersistWorkflow``` and ```CreateEventSubsctiption``` workflow stops forever. 
Declared method in ```IWorkflowRepository``` and implemented for all persistence providers to persist workflow and subscription within single database transaction. 
**Tests**
Yes
No
Any additional information you'd like to provide?
> Fixed consistency of WorkflowConsumer when persisting workflow

- src/WorkflowCore/Services/BackgroundTasks/QueueConsumer.cs
Added a null check before calling `Wait()` on `DispatchTask`. This way, the `Stop()` method can be called multiple times.
**Tests**
No
No
Fixes #1085
> Make QueueConsumer.Stop() idempotent

- src/WorkflowCore/Services/FluentBuilders/WorkflowBuilder.cs
- test/WorkflowCore.IntegrationTests/Scenarios/ForeachWithCompensationScenario.cs
Fixes a bug reported in #1045 that causes an infinite loop when a compensation is nested inside a branch. The problem is caused by a missed correction of `CompensationStepId` during manipulation of step ids when building a branch.
I've added two `if` statements that do the required correction, similar to the other two `if` blocks.
**Tests**
An integration test was added to cover the situation that causes the bug.
No breaking change.
> Fixes a bug that occures when a compensation is nested in a branch

- src/Directory.Build.props
- src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs
- src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs
MongoDB Driver is throwing an exception when saving a list with no item and in our case we don't have any `subscription`
```
System.ArgumentException: Must contain at least 1 request. (Parameter 'requests') at 
MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken) at 
MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken) at 
WorkflowCore.Persistence.MongoDB.Services.MongoPersistenceProvider.PersistWorkflow(WorkflowInstance workflow, List`1 subscriptions, CancellationToken cancellationToken)
```
> [Bug] Fix MongoDB persist workflow when no subscription

- src/WorkflowCore/Interface/IWorkflowModifier.cs
- src/WorkflowCore/Services/FluentBuilders/StepBuilder.cs
- src/WorkflowCore/Services/FluentBuilders/WorkflowBuilder.cs
- src/extensions/WorkflowCore.Users/ServiceExtensions/StepBuilderExtensions.cs
Added new overloads for If/When/ForEach and UserTask with IStepExecutionContext
This allow using these tasks within a loop.
Solves: #599,#338
I copy/pasted the existing implementations and added IStepExecutionContext to the parameters.
**Tests**
No, let me know if they're needed.
No
No
> Add context to If When ForEach and UserTask

- src/providers/WorkflowCore.Providers.AWS/README.md
- src/providers/WorkflowCore.Providers.AWS/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Providers.AWS/Services/DynamoDbProvisioner.cs
- src/providers/WorkflowCore.Providers.AWS/Services/DynamoLockProvider.cs
- src/providers/WorkflowCore.Providers.AWS/Services/DynamoPersistenceProvider.cs
- src/providers/WorkflowCore.Providers.AWS/Services/KinesisProvider.cs
- src/providers/WorkflowCore.Providers.AWS/Services/KinesisStreamConsumer.cs
- src/providers/WorkflowCore.Providers.AWS/Services/KinesisTracker.cs
- src/providers/WorkflowCore.Providers.AWS/Services/SQSQueueProvider.cs
- test/WorkflowCore.Tests.DynamoDB/DynamoPersistenceProviderFixture.cs
Added the option to provide an existing SQS client or Dynamo client rather than having the lock , persistence and queue providers creating them.  
Added additional Service Collection extension methods to allow providing the clients. For default / current behaviour, the clients are now created in the extension method. For the new functionality, the client is passed into the extension method.  The constructors on each of the providers has been altered receive the client rather than create it itself
**Tests**
No changes to functionality - only to how the objects are created
This is not a breaking change as the existing methods and signatures remain and work in the same way
Using …
> Enable supply of pre-provisoned AWS clients

- src/Directory.Build.props
- src/WorkflowCore/Services/WorkflowActivity.cs
In WorkflowActivity.Enrich(WorkflowStep workflowStep) there was a check for a null or empty WorkflowStep.Name and "inline" was used in it's place in the activity display name. A line immediately after referenced WorkflowStep.Name without that check and causes a NullReferenceException if System.Diagnostics.ActivitySource & System.Diagnostics.Activity are used by the host or workflow implementation.
Replaced workflowStep.Name with stepName defined several lines above which either contains the name or "inline" for unnamed steps (Sagas, Snline, etc).
**Tests**
Did you cover your changes with tests? No.
Do you changes break compatibility with previous versions? No.
As far as I can tell …
> Fixed usage of null WorkflowStep.Name in WorkflowActivity diagnostic service.

- src/WorkflowCore/Services/BackgroundTasks/EventConsumer.cs
- src/WorkflowCore/Services/BackgroundTasks/RunnablePoller.cs
- src/WorkflowCore/Services/BackgroundTasks/WorkflowConsumer.cs
- src/WorkflowCore/Services/WorkflowController.cs
- src/WorkflowCore/Services/WorkflowExecutor.cs
https://github.com/danielgerlag/workflow-core/issues/1072
> the names of the fields in the logs have been changed

- src/providers/WorkflowCore.Persistence.EntityFramework/WorkflowCore.Persistence.EntityFramework.csproj
- src/providers/WorkflowCore.Persistence.MySQL/WorkflowCore.Persistence.MySQL.csproj
- src/providers/WorkflowCore.Persistence.PostgreSQL/WorkflowCore.Persistence.PostgreSQL.csproj
- src/providers/WorkflowCore.Persistence.SqlServer/WorkflowCore.Persistence.SqlServer.csproj
- src/providers/WorkflowCore.Persistence.Sqlite/WorkflowCore.Persistence.Sqlite.csproj
- test/Directory.Build.props
Upgrade target framework from net6 to net 8
Upgrade EF7 to EF8 for net8 framework
**Tests**
All current tests pass, there shouldn't be a need for new tests. Only an additional target framework net8 added
This is NOT backwards compatible with EF core 7 or lower.
> Upgrade to net8 and EF8

- src/providers/WorkflowCore.Persistence.EntityFramework/ExtensionMethods.cs
Added JsonSerializerSetting `ObjectCreationHandling = ObjectCreationHandling.Replace` to fix the issue with deserialization of the list items being duplicated. Issue #1270
> #1270 Fixed list items deserialization duplication

- src/samples/WorkflowCore.Sample09s/Program.cs
The correct workflow name for Sample09s is "ForeachSync" not "Foreach".
> Update correct workflow name for Sample09s

- src/providers/WorkflowCore.Providers.Azure/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Providers.Azure/Services/CosmosClientFactory.cs
Added CosmosClientOptions to UseCosmosDbPersistence method and CosmosClientFactory constructor to pass additional configuration over to the CosmosClient.
Added CosmosClientOptions to UseCosmosDbPersistence method and CosmosClientFactory constructor with a default value of "null" so as not to break existing codebases.
**Tests**
N/A
No.
By default, CosmosClient uses the "Direct" ConnectionMethod. This does not always work. To fix this, I wanted to pass the "ConnectionMethod" option. But looking at other providers "ElasticSearch", I saw that the configuration object for ElasticClient was passed to the DI methods. So, I used a similar approach here.
> Added CosmosClientOptions to UseCosmosDbPersistence method and CosmosClientFactory constructor

- src/providers/WorkflowCore.QueueProviders.RabbitMQ/Services/RabbitMQProvider.cs
- src/providers/WorkflowCore.QueueProviders.RabbitMQ/WorkflowCore.QueueProviders.RabbitMQ.csproj
Update the RabbitMq Client library to the latest stable [6.8.1](https://github.com/rabbitmq/rabbitmq-dotnet-client/releases/tag/v6.8.1)
The only breaking change that regard workflow core is consumer delivery payloads are now [ReadOnlyMemory<byte>](https://learn.microsoft.com/en-us/dotnet/api/system.readonlymemory-1?view=net-8.0) instead of byte[]
in [.netstandart 2.1](https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding.getstring?view=netstandard-2.1#System_Text_Encoding_GetString_System_ReadOnlySpan_System_Byte__) we could do .Span()
in [.netstandart 2.0](https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding.getstring?view=netstandard-2.0#System_Text_Encoding_GetString_System_ReadOnlySpan_System_By …
> Feat update rabbitmq

- src/WorkflowCore/Services/WorkflowActivity.cs
Corrected additional null reference errors in Activity enrichment methods.
Using null collescing operator and null checks where necessary to ensure WorkflowStep properties and Activity.Current were not null before using them
**Tests**
No
No
Missed these in my original submission
> Fix morenullrefs in workflow activity

- src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs
- test/WorkflowCore.Tests.MongoDB/MongoPersistenceProviderFixture.cs
Fixed usage of CreateIndexes for MongoPersistenceProvider.cs to avoid database connection already opening during ioc.
Doing database operations in constructor of services that are registered in ioc is dangerous.
In case of connection error the application will crash during ioc already.
I checked how EntityFrameworkPersistenceProvider does database changes and its done in EnsureStoreExists there.
https://github.com/danielgerlag/workflow-core/blob/master/src/providers/WorkflowCore.Persistence.EntityFramework/Services/EntityFrameworkPersistenceProvider.cs#L192
**Tests**
I adjusted the MongoPersistenceProviderFixture to call EnsureStoreExists like its done for the other Providers too.
Change should be …
> Fixed usage of CreateIndexes for mongo

- src/providers/WorkflowCore.Providers.Azure/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Providers.Azure/Services/CosmosClientFactory.cs
> add cosmos mi

- src/providers/WorkflowCore.Persistence.MongoDB/WorkflowCore.Persistence.MongoDB.csproj
- test/WorkflowCore.Tests.MongoDB/WorkflowCore.Tests.MongoDB.csproj
Upgrading mongo to version 2.30. MongoDb started strong naming their packages with plenty of pushback. However it appears they are committed to this change, and therefore needing all projects to upgrade to 2.28+.  A major version 3.0 exists, but would require more testing than just this upgrade and ensure builds are passing.
Discussion on the change:
https://www.mongodb.com/community/forums/t/net-c-driver-strong-naming/291649/16
> Upgrade to Mongo Version 2.30

- src/samples/WebApiSample/WebApiSample/Startup.cs
Endpoint Routing does not support UseMvc
Error Detail :
Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)'. To use 'IApplicationBuilder.UseMvc' set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices(...).
> Fix Error Endpoint Routing does not support UseMvc

- .github/workflows/dotnet.yml
- src/providers/WorkflowCore.Persistence.SqlServer/WorkflowCore.Persistence.SqlServer.csproj
- test/Directory.Build.props
- test/WorkflowCore.Tests.SqlServer/WorkflowCore.Tests.SqlServer.csproj
Describe the change
Add net9 target framework for SqlServer
Tests
All current tests pass, there shouldn't be a need for new tests. Only an additional target framework net9 added
> Upgrade Persistence.SqlServer to use net9

- src/providers/WorkflowCore.LockProviders.SqlServer/SqlLockProvider.cs
- src/providers/WorkflowCore.LockProviders.SqlServer/WorkflowCore.LockProviders.SqlServer.csproj
Replacing vulnerable System.Data.SqlClient dependency in the LockProviders.SqlServer project with Microsoft.Data.SqlClient version used by  Persistence.SqlServer project.
Closes #1368
> #1368: SqlClient dependency update to fix vulnerability

- .github/workflows/dotnet.yml
- README.md
- docs/persistence.md
- src/providers/WorkflowCore.Persistence.Oracle/MigrationContextFactory.cs
- src/providers/WorkflowCore.Persistence.Oracle/OracleContext.cs
- src/providers/WorkflowCore.Persistence.Oracle/OracleContextFactory.cs
- src/providers/WorkflowCore.Persistence.Oracle/README.md
- src/providers/WorkflowCore.Persistence.Oracle/ServiceCollectionExtensions.cs
- src/providers/WorkflowCore.Persistence.Oracle/WorkflowCore.Persistence.Oracle.csproj
- test/WorkflowCore.Tests.Oracle/OraclePersistenceProviderFixture.cs
- test/WorkflowCore.Tests.Oracle/OracleSetup.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleActivityScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleBasicScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleDataScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleDelayScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleDynamicDataScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleEventScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleForeachScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleForkScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleIfScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleRetrySagaScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleSagaScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleUserScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleWhenScenario.cs
- test/WorkflowCore.Tests.Oracle/Scenarios/OracleWhileScenario.cs
- test/WorkflowCore.Tests.Oracle/WorkflowCore.Tests.Oracle.csproj
This PR adds .NET 8.0 support to the Oracle persistence provider and improves the overall test infrastructure and documentation. The main highlight is the addition of .NET 8.0 compatibility, making the Oracle provider fully supported on the latest .NET version.
- **Added .NET 8.0 support**: Updated the Oracle persistence provider to target .NET 8.0 alongside existing .NET 6.0 support
- **Improved test infrastructure**: 
- Added Oracle tests to the GitHub CI/CD pipeline
- Fixed Oracle tests using TestContainers for reliable containerized testing
- Added .NET 8.0 test support for Oracle scenarios
- **Enhanced documentation**: 
- Improved Oracle persistence README with better usage examples and configuration details
- Added …
> feat: Add .NET 8.0 support for Oracle persistence provider and improve test infrastructure
